#############################################################################
# Makefile for building: PassiveNetwork
# Generated by qmake (2.01a) (Qt 4.6.3) on: mar set 20 23:17:48 2011
# Project:  PassiveNetwork.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile PassiveNetwork.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -lqscintilla2 -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		tcpserver.cpp \
		tcpreceiver.cpp \
		qhexedit2/qhexedit_p.cpp \
		qhexedit2/qhexedit.cpp moc_mainwindow.cpp \
		moc_tcpserver.cpp \
		moc_tcpreceiver.cpp \
		moc_qhexedit.cpp \
		moc_qhexedit_p.cpp \
		qrc_icons.cpp
OBJECTS       = main.o \
		mainwindow.o \
		tcpserver.o \
		tcpreceiver.o \
		qhexedit_p.o \
		qhexedit.o \
		moc_mainwindow.o \
		moc_tcpserver.o \
		moc_tcpreceiver.o \
		moc_qhexedit.o \
		moc_qhexedit_p.o \
		qrc_icons.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		PassiveNetwork.pro
QMAKE_TARGET  = PassiveNetwork
DESTDIR       = 
TARGET        = PassiveNetwork

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: PassiveNetwork.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtNetwork.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile PassiveNetwork.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtNetwork.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile PassiveNetwork.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/PassiveNetwork1.0.0 || $(MKDIR) .tmp/PassiveNetwork1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/PassiveNetwork1.0.0/ && $(COPY_FILE) --parents mainwindow.h tcpserver.h tcpreceiver.h qhexedit2/qhexedit.h qhexedit2/qhexedit_p.h .tmp/PassiveNetwork1.0.0/ && $(COPY_FILE) --parents icons.qrc .tmp/PassiveNetwork1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp tcpserver.cpp tcpreceiver.cpp qhexedit2/qhexedit_p.cpp qhexedit2/qhexedit.cpp .tmp/PassiveNetwork1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/PassiveNetwork1.0.0/ && (cd `dirname .tmp/PassiveNetwork1.0.0` && $(TAR) PassiveNetwork1.0.0.tar PassiveNetwork1.0.0 && $(COMPRESS) PassiveNetwork1.0.0.tar) && $(MOVE) `dirname .tmp/PassiveNetwork1.0.0`/PassiveNetwork1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/PassiveNetwork1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_tcpserver.cpp moc_tcpreceiver.cpp moc_qhexedit.cpp moc_qhexedit_p.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_tcpserver.cpp moc_tcpreceiver.cpp moc_qhexedit.cpp moc_qhexedit_p.cpp
moc_mainwindow.cpp: tcpserver.h \
		tcpreceiver.h \
		qhexedit2/qhexedit.h \
		qhexedit2/qhexedit_p.h \
		mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_tcpserver.cpp: tcpserver.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) tcpserver.h -o moc_tcpserver.cpp

moc_tcpreceiver.cpp: tcpreceiver.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) tcpreceiver.h -o moc_tcpreceiver.cpp

moc_qhexedit.cpp: qhexedit2/qhexedit_p.h \
		qhexedit2/qhexedit.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) qhexedit2/qhexedit.h -o moc_qhexedit.cpp

moc_qhexedit_p.cpp: qhexedit2/qhexedit_p.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) qhexedit2/qhexedit_p.h -o moc_qhexedit_p.cpp

compiler_rcc_make_all: qrc_icons.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_icons.cpp
qrc_icons.cpp: icons.qrc \
		fileopen.svg \
		info.svg \
		gtk-help.svg \
		filesaveas.svg \
		gnome-fs-network.svg
	/usr/bin/rcc -name icons icons.qrc -o qrc_icons.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/usr/bin/uic-qt4 mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		tcpserver.h \
		tcpreceiver.h \
		qhexedit2/qhexedit.h \
		qhexedit2/qhexedit_p.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		tcpserver.h \
		tcpreceiver.h \
		qhexedit2/qhexedit.h \
		qhexedit2/qhexedit_p.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

tcpserver.o: tcpserver.cpp tcpserver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tcpserver.o tcpserver.cpp

tcpreceiver.o: tcpreceiver.cpp tcpreceiver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tcpreceiver.o tcpreceiver.cpp

qhexedit_p.o: qhexedit2/qhexedit_p.cpp qhexedit2/qhexedit_p.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qhexedit_p.o qhexedit2/qhexedit_p.cpp

qhexedit.o: qhexedit2/qhexedit.cpp qhexedit2/qhexedit.h \
		qhexedit2/qhexedit_p.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qhexedit.o qhexedit2/qhexedit.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_tcpserver.o: moc_tcpserver.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tcpserver.o moc_tcpserver.cpp

moc_tcpreceiver.o: moc_tcpreceiver.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tcpreceiver.o moc_tcpreceiver.cpp

moc_qhexedit.o: moc_qhexedit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qhexedit.o moc_qhexedit.cpp

moc_qhexedit_p.o: moc_qhexedit_p.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qhexedit_p.o moc_qhexedit_p.cpp

qrc_icons.o: qrc_icons.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_icons.o qrc_icons.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

